version: 0.1.{build}

init:
    - git config --global core.autocrlf input

shallow_clone: true
skip_branch_with_pr: true

matrix:
    fast_finish: true

platform:
    - x64

configuration:
    - Release

environment:
    matrix:
        - job_name: macOS build
          appveyor_build_worker_image: macos

        - job_name: Windows build
          appveyor_build_worker_image: Visual Studio 2017

for:
    -
        matrix:
          only:
            - job_name: macOS build
        clone_folder: /Users/appveyor/projects/CodeMore
        build_script:
            - brew install qt5
            - export PATH="/usr/local/opt/qt/bin:$PATH"
            - mkdir build
            - cd build
            - cmake -G "Unix Makefiles" .. -DCMAKE_PREFIX_PATH=/usr/local/top/qt
            - cmake --build . --config Release
            - macdeployqt CodeMore.app -qmldir=/usr/local/opt/qt/qml -dmg
            - sh ../ci/scripts/macos/make_macos_installer.sh CodeMore $(cat < ../version)
        artifacts:
            - path: build\CodeMore.*.dmg

    -
        matrix:
          only:
            - job_name: Windows build
        clone_folder: c:\projects\CodeMore
        build_script:
            - set PATH=c:\Qt\5.12.6\msvc2017_64\bin;%PATH%
            - echo %PATH%
            - mkdir build
            - cd build
            - cmake -G "Visual Studio 15 2017 Win64" .. -DCMAKE_PREFIX_PATH=C:\Qt\5.12.6\msvc2017_64
            - cmake --build . --config Release
            - c:\Qt\5.12.6\msvc2017_64\bin\windeployqt --qmldir C:\Qt\5.12.6\msvc2017_64\qml %APPVEYOR_BUILD_FOLDER%\build\Release\CodeMore.exe
        after_build:
            - cmd: 7z a CodeMore.zip %APPVEYOR_BUILD_FOLDER%\build\Release\*
        artifacts:
            - path: build\CodeMore.zip

install:

deploy:
    - provider: GitHub
      auth_token:
        secure: XDu4+kIKFFYWIc3yR7x9eX1kWZzF5aBmItTxzytX+Rwy5bwazcAHuN+wzOe8XkOE
      draft: false
      prerelease: false
      on:
        branch: master
        APPVEYOR_REPO_TAG: true 

